### PR TITLE
posthtml-cli example

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by andreyvolokitin** [comment]
Should it work with along with ```posthtml-loader```? I am getting this error in my codebase:
```
> posthtml dist/*.html

{}
TypeError: Cannot read property 'query' of undefined
    at Object.getOptions (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/loader-utils/lib/getOptions.js:6:30)
    at loader (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml-loader/lib/index.js:38:31)
    at /Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/post-load-plugins/lib/index.js:1:2380
    at Array.map (<anonymous>)
    at /Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/post-load-plugins/lib/index.js:1:2307
    at PostHTML.<anonymous> (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml/lib/index.js:179:7)
    at /Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml/lib/index.js:210:5
    at new Promise (<anonymous>)
    at PostHTML.process (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml/lib/index.js:209:10)
    at /Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml-cli/lib/cli.js:21:943
```

**Comment by andreyvolokitin** [comment]
Yep, it does not working with ```posthtml-loader``` installed. Very strange

**Comment by andreyvolokitin** [comment]
Another problem: now I can't use non-cli ```posthtml```. With [this field](https://github.com/andreyvolokitin/posthtml-beautify-test/pull/2/commits/4ae98819c1ccb814f522853a370d96ecc2ebe6c2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17) in my ```package.json``` non-cli ```posthtml``` stops working completely

**Comment by Scrum** [comment]
update this example

**Comment by andreyvolokitin** [comment]
[Done](https://github.com/andreyvolokitin/posthtml-beautify-test/commit/acf84fbb91f5ce441524c90b6d2b3785be596a76). Details on the second problem: ```posthtml``` works if I define plugin options inside ```webpack.config.js```, but not when I define them inside ```posthtml.config.js```

**Comment by Scrum** [comment]
@andreyvolokitin [fix](https://github.com/andreyvolokitin/posthtml-beautify-test/pull/3)

**Pull request merged**
