### PR TITLE
fix example

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by andreyvolokitin** [comment]
Thanks, still have [this problem](https://github.com/andreyvolokitin/posthtml-beautify-test/pull/2#issuecomment-367972081) in my codebase but it's gone in this example. Investigating...

**Comment by andreyvolokitin** [comment]
@Scrum okay, I got it: ```posthtml.config.js``` is not loaded/applied when I have ```posthtml``` [field](https://github.com/andreyvolokitin/posthtml-beautify-test/pull/2/commits/4ae98819c1ccb814f522853a370d96ecc2ebe6c2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17) in ```package.json```, but it is loaded/applied as expected if I delete ```posthtml``` field from ```package.json```. [See updated example](https://github.com/andreyvolokitin/posthtml-beautify-test/commit/711a234ac84f9292af5405f0d46ea8126ba6f9b9): it prints string "TEST" in the console after ```npm run build``` which means ```posthtml.config.js``` is loaded correctly. But try to revert ```package.json``` to its [previous state](https://github.com/andreyvolokitin/posthtml-beautify-test/blob/b60428372009cbfbabb4cab08ad231faddcfc5f7/package.json) (with ```posthtml``` field) and run ```npm run build```: then there is no test string in a console output, though ```posthtml-include``` still works with some "default" settings

**Comment by andreyvolokitin** [comment]
I think that's the cause: https://github.com/posthtml/posthtml-load-config#packagejson

**Comment by andreyvolokitin** [comment]
I tried setting another config for ```posthtml-cl```: ```posthtml dist/*.html -c posthtml-cli.config.js```. The contents is following:
```js
module.exports = {
  plugins: [
    require('posthtml-beautify')({
        blankLines: false,
        test: console.log('Config 2'),
    }),
  ],
};
```
...but it throws this:
```bash
{ YAMLException: end of the stream or a document separator is expected at line 2, column 10:
      plugins: [
             ^
    at generateError (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at methods (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/get-cff/lib/index.js:1:1083)
    at /Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/get-cff/lib/index.js:1:1310
    at flatrySync (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/flatry/index.js:5:19)
    at flatry (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/flatry/index.js:23:56)
  name: 'YAMLException',
  reason: 'end of the stream or a document separator is expected',
  mark:
   Mark {
     name: null,
     buffer: 'module.exports = {\n  plugins: [\n    require(\'posthtml-beautify\')({\n        blankLines: false,\n        test: console.log(\'Config 2\'),\n    }),\n  ],\n};\n\u0000',
     position: 28,
     line: 1,
     column: 9 },
  message: 'end of the stream or a document separator is expected at line 2, column 10:\n      plugins: [\n             ^' }
```
I think it interprets JS file as YAML somewhere here: https://github.com/Scrum/get-cff/blob/master/src/index.js but not sure why...

**Comment by andreyvolokitin** [comment]
So ```require``` [here](https://github.com/Scrum/get-cff/blob/master/src/index.js#L6) does not work with a relative path to the config in a CLI command (```posthtml dist/*.html -c posthtml-cli.config.js```), but it works with an absolute path. And still, ```posthtml-beautify``` does not execute properly (there are blank lines in the output). See this: https://github.com/andreyvolokitin/posthtml-beautify-test/commit/4d6df8a3e3e73aec85bda185e8e4acc1519390e5

**Comment by Scrum** [comment]
> YAMLException: end of the stream or a document separator is expected at line 2, column 10:

I could not reproduce this error, I need more details

**Comment by Scrum** [comment]
> And still, posthtml-beautify does not execute properly (there are blank lines in the output)

- [ ] https://github.com/post/post-load-plugins/issues/145

> So require here does not work with a relative path to the config in a CLI command (posthtml dist/*.html -c posthtml-cli.config.js), but it works with an absolute path.

- [x] https://github.com/posthtml/posthtml-cli/issues/273

### If there is a desire to support these products, I can give you access to the repositories of interest to you

**Comment by andreyvolokitin** [comment]
This error occurs if you use a relative path [here ](https://github.com/andreyvolokitin/posthtml-beautify-test/commit/4d6df8a3e3e73aec85bda185e8e4acc1519390e5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R23) (`posthtml-cli.config.js`) in [this branch](https://github.com/andreyvolokitin/posthtml-beautify-test/tree/multi-config). 

Thanks, but for now I think a regular PRs would be enough for me, because I suppose my contributions still need to be validated, and there probably won't be a lot of them

**Comment by Scrum** [comment]
> This error occurs if you use a relative path here (posthtml-cli.config.js) in this branch.

not reproduce

**Comment by Scrum** [comment]
> This error occurs if you use a relative path here (posthtml-cli.config.js) in this branch.

could not reproduce

**Comment by andreyvolokitin** [comment]
Check this: https://github.com/andreyvolokitin/posthtml-beautify-test/commit/c20eb9aba586a7f7eee1b609692863765c005f4f. Maybe it was because of contents of `index.html`

**Comment by Scrum** [comment]
no, it does not reproduce, all processes occur normally

**Comment by andreyvolokitin** [comment]
Very strange... So you effectively also can't reproduce this [opened issue](https://github.com/posthtml/posthtml-cli/issues/273)? Just in case: Node `v9.2.1`, npm `5.7.1`, OS X 10.11.6

**Comment by Scrum** [comment]
> Very strange... So you effectively also can't reproduce this opened issue?

I did not check at the time, did the task to not forget

**Comment by andreyvolokitin** [comment]
Yeah, apparently it's not about a bug in a code. `require('posthtml-cli.config.js')` simply doesn't find/see existing file by relative path,  while `process.cwd()` is returning project root folder as expected, and node `path.resolve()` also resolving this relative path to an absolute path correctly

**Comment by andreyvolokitin** [comment]
In fact, `require` can't see any .js file by relative path. I am sure the reason for this is simple, but I think I am going to abandon this voodoo magic and just edit `get-cff` to resolve to absolute path

**Comment by andreyvolokitin** [comment]
Hmm, reading [this](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8#7387) and it says `require('posthtml-cli.config.js')` is looking for a *package* in some set of `node_modules` folders (`module.paths`). While `require('./posthtml-cli.config.js')` is looking a *file* by a relative path (which I also can't got working). How this command `require('posthtml-cli.config.js')` is finding non-existing `*/node_modules/posthtml-cli.config.js` OR simply `./posthtml-cli.config.js`  on your machine is beyond my undersanding

**Comment by andreyvolokitin** [comment]
OKay, another try. [In this branch](https://github.com/andreyvolokitin/posthtml-beautify-test/tree/multi-config) open a file `node_modules/get-cff/lib/index.js`. Insert `console.log(path);` before this string: `return method(path)`. The log in a console should output `posthtml-cli.config.js` few times. Now the question is: is it expected for `method('posthtml-cli.config.js')` to work if `method === require`? Isn't it means that it will try to require a *node module* called "posthtml-cli.config.js", but not a file? ([here is related untranspiled code](https://github.com/Scrum/get-cff/blob/master/src/index.js#L15))

**Comment by Scrum** [comment]
@andreyvolokitin catched, thanks

**Comment by Scrum** [comment]
https://github.com/andreyvolokitin/posthtml-beautify-test/pull/4

**Comment by andreyvolokitin** [comment]
> post/post-load-plugins#145

In this example, I found that: 
- html is beautified even if I remove `posthtml-beautify` from config ([wat](http://i0.kym-cdn.com/photos/images/newsfeed/000/173/576/Wat8.jpg))
- when I define `posthtml-beautify` in a config — it is not respecting options from this definition (so it uses default `blankLines`)

**Comment by andreyvolokitin** [comment]
I am not even sure now how these configs/options work/should work... I thought that with each posthtml invocation there is a single config in use which strictly defines all plugins/options, but it looks like it's not. Because in my codebase I'm getting even more bizarre bugs. I.e. I have a plugin in *config 1* which somehow executing and causing errors while `posthtml-cli` is executing with *config 2* which doesn't define this plugin

**Comment by Scrum** [comment]
[post-load-plugins](https://github.com/post/post-load-plugins) clearly dictates how to configure the configuration

**Comment by andreyvolokitin** [comment]
Looks like `post-config` is [parsing](https://github.com/post/post-config/blob/master/src/index.js#L123) whole `node_modules` directory, so any installed posthtml plugins are detected, and later presumably used automatically even without explicit config. Is that a correct behavior? If so, then presumably an explicit posthtml config should overwrite this, so that plugins which are absent in config definition aren't invoked. But in this example they not only invoked, but also their options are kept being default despite same plugin options from explicit config

Also `post-load-plugins` seems to [have proper config options here](https://github.com/post/post-load-plugins/blob/master/src/index.js#L32) (`options`), but after execution of `postConfig` and `postSequence` the `config` variable holds a config that may contain plugins which a not specified in explicit posthtml config, or it may contain plugins with default options while ignoring options defined in an explicit posthtml config

**Comment by andreyvolokitin** [comment]
I forgot to [RTFM](https://github.com/post/post-load-plugins#usage): 

> For plugins not having configuration installed locally will be used default settings.

Also [this](https://github.com/post/post-load-plugins#why):

> post-config - Automatically detect all plugins installed and create a configuration for them **from the description in package.json used in the process**.

It explains everything. All installed plugins are executed with default options by design. Also `post-config` not taking external config into account and only uses config inside `package.json`, that's why it keeps using default `beautify` options while ignoring config `beautify` options.

**Comment by Scrum** [comment]
Thank you for your interest 👍 

> s that a correct behavior?

Yep

> Also post-load-plugins seems to have proper config options here (options), but after execution of postConfig and postSequence the config variable holds a config that may contain plugins which a not specified in explicit posthtml config, or it may contain plugins with default options while ignoring options defined in an explicit posthtml config

https://github.com/post/post-load-plugins/issues/145

No desire to deal with these issues once already deepened?

**Comment by andreyvolokitin** [comment]
I'll try to do that

- _auto-invoking of installed plugins:_ maybe implementing some flag in a config can solve this, like `skipUndeclaredPlugins: true`? This is quite an issue in a multi-config scenario (which is not common at all), because we have all plugins executing every time while we only want a subset of installed plugins on each execution (i.e. CLI vs non-CLI). But also this is a "major change" that can affect the whole ecosystem — who knows how many plugins/modules should be edited to make use of this new flag? I can say with confidence that I know very little about the whole ecosystem
- _ignoring plugin options in external config by `post-load-plugins`/`post-config`:_ is it expected behavior? I assume so, because it says only about `package.json ` in a readme and I made it work with a config within `package.json`, but not with external config. Probably there is something wrong with `posthtml-load-config`/`posthtml-load-options` then? Because it seems like they in charge of loading/applying external configs/options

**Comment by andreyvolokitin** [comment]
By "multi-config" I mean 2 external configs, excluding `package.json` (it can't be used separately anyway)

**Comment by andreyvolokitin** [comment]
BTW by now I think if it all worth it. Maybe just use a single posthtml execution? Is there any real value in [multi-config scenario](https://github.com/Scrum/posthtml-beautify/issues/216#issuecomment-358279289)? Yes, `html-webpack-plugin` will make my html little uglier in the end, after `posthtml-beautify` is already done processing. But I think it is minor issue comparing to implementing a whole new feature in posthtml and shooting down some mysterious bugs. With a single non-CLI execution and a single config — it all works. Though it would be nice to make this multi-config use case working

**Comment by andreyvolokitin** [comment]
Here is proper `beautify` options definition, I got it wrong earlier: https://github.com/andreyvolokitin/posthtml-beautify-test/commit/a03db659c935e22d7641ad3cd278abcc273512c8

**Comment by Scrum** [comment]
> auto-invoking of installed plugins: maybe implementing some flag in a config can solve this, like skipUndeclaredPlugins: true? 

you can simply not include them in the general concatenation only to check for existence based on the incoming config, but then it all makes sense. I describe the config itself

> ignoring plugin options in external config by post-load-plugins/post-config: is it expected behavior? 

I do not think, because We do not know what else will come with the dependencies and the situation is possible when we have to describe too much

> By "multi-config" I mean 2 external configs, excluding package.json (it can't be used separately anyway)

in my understanding, this is the priority of configs starting from the command line the highest priority then the incoming config and the configuration created automatically but now the instantiated plugins

and to be honest, I have already lost the thread of the event))

**Comment by andreyvolokitin** [comment]
> you can simply not include them in the general concatenation only to check for existence based on the incoming config, but then it all makes sense. I describe the config itself

Yes, but this may be quite radical "breaking change", because if someone currently is relying on auto-invoking of all installed plugins (and this behavior is documented in a readme), then they will be surprised when it suddenly stop working. With a flag the current behavior can be preserved and new behavior introduced only when actually needed

> I do not think, because We do not know what else will come with the dependencies and the situation is possible when we have to describe too much

So you're saying this is a bug and `post-load-plugins` / `post-config` should apply plugin options from external config? Check [this](https://github.com/post/post-load-plugins#why): «post-config - Automatically detect all plugins installed and create a configuration for them **from the description in package.json** used in the process.». I checked it: it applying options only from configuration inside `package.json`, but not from configuration from external files like `posthtml.config.js`

> in my understanding, this is the priority of configs starting from the command line the highest priority then the incoming config and the configuration created automatically but now the instantiated plugins

Yeah, this is a priority of configs. But *which* configs end up in this priority — this is the question. When we have 2 separate posthtml executions, like in this repo ( 1 — regular posthtml; and 2 — posthtml-cli), then for each execution we have such priority of configs, but for each execution we also provide/define its own *separate* external config (like `posthtml_1.config.js` and `posthtml_2.config.js`). Then with each execution, there is a priority: command line config >> package.json config >> external.config.js. And external config is what differs for each execution, and also external config is the only way (aside from CLI settings) to describe a distinct/separate config for each execution. That is what I thought and that's why I chose to have 2 external configs in this repo (`posthtml.config.js` and `posthtml-cli.config.js`), and *not* a second config inside `package.json` which would've been applied on each execution

**Comment by andreyvolokitin** [comment]
> and to be honest, I have already lost the thread of the event))

That's okay, currently I'm considering to use a single regular posthtml process, so maybe all these problems will become irrelevant (at least for me). I'm not even sure if they are worth investigating. Yeah, auto-invoking of all installed plugins is weird, but that is what needed in most cases with single posthtml process anyway. And regarding ignoring options from external config... I think this may be a specific issue of posthtml-cli, because with regular posthtml there are no problems

**Comment by andreyvolokitin** [comment]
I will make reduced testcases and try to create issues in proper repos

**Comment by Scrum** [comment]
> Yes, but this may be quite radical "breaking change", because if someone currently is relying on auto-invoking of all installed plugins (and this behavior is documented in a readme), then they will be surprised when it suddenly stop working. With a flag the current behavior can be preserved and new behavior introduced only when actually needed

I meant the settings `post-config` if you enter an option `skipUndeclaredPlugins: true`

> but not from configuration from external files like posthtml.config.js

The config that is given in your example `posthtml.config.js` in such notation is used by the package ` posthtml-load-config` these are completely unrelated packages with `post-load-plugins` 😄 .
For this package - it has not yet been implemented

> Check this: «post-config - Automatically detect all plugins installed and create a configuration for them from the description in package.json used in the process.». I checked it: it applying options only from configuration inside package.json

I know because I'm the creator 😄 

> I will make reduced testcases and try to create issues in proper repos

Thank you, if necessary, I will provide all the accesses

**Comment by Scrum** [comment]
so we can communicate in https://gitter.im/Scrum  Russian)

**Pull request merged**
